/*-
 * Copyright (C) 2022-2024 Confluent, Inc.
 */

/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka.client.smart.integration.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EmployeeAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1531136687008561002L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeAvro\",\"namespace\":\"csid.client.integration.model\",\"fields\":[{\"name\":\"ID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"Name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"Email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"Age\",\"type\":\"int\"},{\"name\":\"SSN\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmployeeAvro> ENCODER =
      new BinaryMessageEncoder<EmployeeAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmployeeAvro> DECODER =
      new BinaryMessageDecoder<EmployeeAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EmployeeAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EmployeeAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EmployeeAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmployeeAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EmployeeAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EmployeeAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EmployeeAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EmployeeAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String ID;
  private java.lang.String Name;
  private java.lang.String Email;
  private int Age;
  private int SSN;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmployeeAvro() {}

  /**
   * All-args constructor.
   * @param ID The new value for ID
   * @param Name The new value for Name
   * @param Email The new value for Email
   * @param Age The new value for Age
   * @param SSN The new value for SSN
   */
  public EmployeeAvro(java.lang.String ID, java.lang.String Name, java.lang.String Email, java.lang.Integer Age, java.lang.Integer SSN) {
    this.ID = ID;
    this.Name = Name;
    this.Email = Email;
    this.Age = Age;
    this.SSN = SSN;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID;
    case 1: return Name;
    case 2: return Email;
    case 3: return Age;
    case 4: return SSN;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID = value$ != null ? value$.toString() : null; break;
    case 1: Name = value$ != null ? value$.toString() : null; break;
    case 2: Email = value$ != null ? value$.toString() : null; break;
    case 3: Age = (java.lang.Integer)value$; break;
    case 4: SSN = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ID' field.
   * @return The value of the 'ID' field.
   */
  public java.lang.String getID() {
    return ID;
  }


  /**
   * Sets the value of the 'ID' field.
   * @param value the value to set.
   */
  public void setID(java.lang.String value) {
    this.ID = value;
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.String getName() {
    return Name;
  }


  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'Email' field.
   * @return The value of the 'Email' field.
   */
  public java.lang.String getEmail() {
    return Email;
  }


  /**
   * Sets the value of the 'Email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.String value) {
    this.Email = value;
  }

  /**
   * Gets the value of the 'Age' field.
   * @return The value of the 'Age' field.
   */
  public int getAge() {
    return Age;
  }


  /**
   * Sets the value of the 'Age' field.
   * @param value the value to set.
   */
  public void setAge(int value) {
    this.Age = value;
  }

  /**
   * Gets the value of the 'SSN' field.
   * @return The value of the 'SSN' field.
   */
  public int getSSN() {
    return SSN;
  }


  /**
   * Sets the value of the 'SSN' field.
   * @param value the value to set.
   */
  public void setSSN(int value) {
    this.SSN = value;
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static EmployeeAvro.Builder newBuilder() {
    return new EmployeeAvro.Builder();
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static EmployeeAvro.Builder newBuilder(EmployeeAvro.Builder other) {
    if (other == null) {
      return new EmployeeAvro.Builder();
    } else {
      return new EmployeeAvro.Builder(other);
    }
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder by copying an existing EmployeeAvro instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static EmployeeAvro.Builder newBuilder(EmployeeAvro other) {
    if (other == null) {
      return new EmployeeAvro.Builder();
    } else {
      return new EmployeeAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for EmployeeAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeAvro>
    implements org.apache.avro.data.RecordBuilder<EmployeeAvro> {

    private java.lang.String ID;
    private java.lang.String Name;
    private java.lang.String Email;
    private int Age;
    private int SSN;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(EmployeeAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Email)) {
        this.Email = data().deepCopy(fields()[2].schema(), other.Email);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.Age)) {
        this.Age = data().deepCopy(fields()[3].schema(), other.Age);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.SSN)) {
        this.SSN = data().deepCopy(fields()[4].schema(), other.SSN);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(EmployeeAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Email)) {
        this.Email = data().deepCopy(fields()[2].schema(), other.Email);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Age)) {
        this.Age = data().deepCopy(fields()[3].schema(), other.Age);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.SSN)) {
        this.SSN = data().deepCopy(fields()[4].schema(), other.SSN);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'ID' field.
      * @return The value.
      */
    public java.lang.String getID() {
      return ID;
    }


    /**
      * Sets the value of the 'ID' field.
      * @param value The value of 'ID'.
      * @return This builder.
      */
    public EmployeeAvro.Builder setID(java.lang.String value) {
      validate(fields()[0], value);
      this.ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID' field has been set.
      * @return True if the 'ID' field has been set, false otherwise.
      */
    public boolean hasID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID' field.
      * @return This builder.
      */
    public EmployeeAvro.Builder clearID() {
      ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return Name;
    }


    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public EmployeeAvro.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.Name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public EmployeeAvro.Builder clearName() {
      Name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Email' field.
      * @return The value.
      */
    public java.lang.String getEmail() {
      return Email;
    }


    /**
      * Sets the value of the 'Email' field.
      * @param value The value of 'Email'.
      * @return This builder.
      */
    public EmployeeAvro.Builder setEmail(java.lang.String value) {
      validate(fields()[2], value);
      this.Email = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Email' field has been set.
      * @return True if the 'Email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Email' field.
      * @return This builder.
      */
    public EmployeeAvro.Builder clearEmail() {
      Email = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Age' field.
      * @return The value.
      */
    public int getAge() {
      return Age;
    }


    /**
      * Sets the value of the 'Age' field.
      * @param value The value of 'Age'.
      * @return This builder.
      */
    public EmployeeAvro.Builder setAge(int value) {
      validate(fields()[3], value);
      this.Age = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Age' field has been set.
      * @return True if the 'Age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Age' field.
      * @return This builder.
      */
    public EmployeeAvro.Builder clearAge() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'SSN' field.
      * @return The value.
      */
    public int getSSN() {
      return SSN;
    }


    /**
      * Sets the value of the 'SSN' field.
      * @param value The value of 'SSN'.
      * @return This builder.
      */
    public EmployeeAvro.Builder setSSN(int value) {
      validate(fields()[4], value);
      this.SSN = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'SSN' field has been set.
      * @return True if the 'SSN' field has been set, false otherwise.
      */
    public boolean hasSSN() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'SSN' field.
      * @return This builder.
      */
    public EmployeeAvro.Builder clearSSN() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmployeeAvro build() {
      try {
        EmployeeAvro record = new EmployeeAvro();
        record.ID = fieldSetFlags()[0] ? this.ID : (java.lang.String) defaultValue(fields()[0]);
        record.Name = fieldSetFlags()[1] ? this.Name : (java.lang.String) defaultValue(fields()[1]);
        record.Email = fieldSetFlags()[2] ? this.Email : (java.lang.String) defaultValue(fields()[2]);
        record.Age = fieldSetFlags()[3] ? this.Age : (java.lang.Integer) defaultValue(fields()[3]);
        record.SSN = fieldSetFlags()[4] ? this.SSN : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmployeeAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmployeeAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmployeeAvro>
    READER$ = (org.apache.avro.io.DatumReader<EmployeeAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ID);

    out.writeString(this.Name);

    out.writeString(this.Email);

    out.writeInt(this.Age);

    out.writeInt(this.SSN);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ID = in.readString();

      this.Name = in.readString();

      this.Email = in.readString();

      this.Age = in.readInt();

      this.SSN = in.readInt();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ID = in.readString();
          break;

        case 1:
          this.Name = in.readString();
          break;

        case 2:
          this.Email = in.readString();
          break;

        case 3:
          this.Age = in.readInt();
          break;

        case 4:
          this.SSN = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










